apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    project: hackmaze
spec:
  type: LoadBalancer
  selector:
    app: fast-backend
  ports:
  - port: 3001
    name: http
    targetPort: 80