apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-rolebindings
  namespace: default
  labels:
    project: hackmaze
subjects:

roleRef:
  kind: Role
  name: devops-role
  apiGroup: rbac.authorization.k8s.io