apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    project: hackmaze
spec:
  type: LoadBalancer
  selector:
    app: react-frontend
  ports:
  - port: 3000
    name: http    
    targetPort: 80
