kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: frontend-network-policy
  labels:
    project: hackmaze
spec:
  podSelector:
    matchLabels:
      role: frontend-role
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 80