apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    project: hackmaze
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000

          - path: /services/?(.*)
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3001

          - path: /monitoring/?(.*)
            pathType: Prefix
            backend:
              service:
                name: grafana-external-service
                port:
                  number:  3000