apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
    project: hackmaze
data:
  POSTGRES_DB: hackmaze
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_SERVER: postgres-service
  POSTGRES_PORT: "5432"
