apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
    project: hackmaze
data:
  POSTGRES_DB: hackmaze
  POSTGRES_USER: postgres
  PGDATA: /var/lib/postgresql/data/pgdata
