apiVersion: v1
kind: Service # Create service
metadata:
  name: postgres # Sets the service name
  labels:
    app: postgres # Defines app to create service for
    project: hackmaze
spec:
  type: NodePort # Sets the service type
  selector:
  app: postgres
  ports:
    - port: 5432 # Sets the port to run the postgres application
      nodePort: 30007