apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: security-clusterrolebindings
  namespace: default
  labels:
    project: hackmaze
subjects:

roleRef:
  kind: ClusterRole
  name: security-clusterrole
  apiGroup: rbac.authorization.k8s.io