apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hackmaze-app
  namespace: default
spec:
  dnsNames:
    - hackmaze.0rg.us
  secretName: hackmaze-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer